name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22297f02fdff84ea87154e9a3b32a3360ad9f1e97fea1715fb07888e875d1a06"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
