name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "531041bb826af2d08639ae9db23d26ede7ca9a81951485f92ca540bce114bf19"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
